[tool.poetry]
name = "dump-project"
version = "0.1.0"
description = ""
authors = ["ezzye <ezzy.elliott@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pathspec = "^0.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
